my:
   greeting: Hello World
   list:
       value: One,Two,three

db:
   connection: "{connectionString:'http://ggggg', userName: 'foo', password: 'pass'}"
   host: 127.0.0.0
   port: 1200

management.endpoints.web.exposure.include: "*"

#spring.profiles.active: test


spring.cloud.config.uri: http://localhost:8888
spring.application.name: spring-boot-configurations